# ===============================================
# |||  الهيكل الصحيح لملف render.yaml   |||
# ===============================================

databases:
  # تعريف قاعدة البيانات في قسمها الخاص
  - name: lims-db
    databaseName: lims_db_production
    user: lims_user
    plan: free

services:
  # خدمة الواجهة الخلفية
  - type: web
    name: lims-backend
    runtime: docker
    plan: free
    repo: https://github.com/zitoun39/LIMS-system99 # تأكد من رابط مستودعك
    envVars:
      - key: DATABASE_URL
        fromDatabase: # <-- لاحظ: تم تغييرها إلى fromDatabase
          name: lims-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: 1

  # خدمة الواجهة الأمامية
  - type: web
    name: lims-frontend
    runtime: docker
    plan: free
    repo: https://github.com/zitoun39/LIMS-system99 # تأكد من رابط مستودعك
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: lims-backend
          property: url
